// Bundles the modules user code can import inside the Dynamic Worker into strings
import { build } from 'esbuild'
import { writeFile } from 'node:fs/promises'

const entries = {
  hono: 'hono',
  // The package in ../src, with Jev wired to the JEV binding
  'hono-jev-router': './src/playground-router.ts',
}

const bundle = async (entry) => {
  const result = await build({
    entryPoints: [entry],
    bundle: true,
    format: 'esm',
    target: 'es2022',
    minify: true,
    write: false,
  })
  return result.outputFiles[0].text
}

const modules = Object.fromEntries(
  await Promise.all(
    Object.entries(entries).map(async ([name, entry]) => [name, await bundle(entry)])
  )
)

await writeFile(
  'src/generated/modules.ts',
  `// Generated by scripts/build-modules.mjs\nexport const modules: Record<string, string> = ${JSON.stringify(modules)}\n`
)
console.log(
  Object.entries(modules)
    .map(([name, js]) => `${name}: ${js.length} bytes`)
    .join(', ')
)
